Locale: en
PilotTool: STICK

# Enables:
# WASD Direct Control w/Keyboard Turning (Sneak-walking sideways in Direct Control)
# The "/dc" Command
# Passengers/Crews (Allows the Pilot to add/remove Players who can 'stick' to their Ship)
# The "/crew <username>" Command, allows the above.
ExtraCommands: true
lockPilotAtDirectControl: true

DisableSpillProtection: false
DisableIceForm: true
SinkCheckTicks: 100
ManOverboardTimeout: 60
ManOverboardDistance: 1000 # maximum distance from a craft that you can manoverboard to it
SilhouetteViewDistance: 200
SilhouetteBlockCount: 20
ProtectPilotedCrafts: true
MaxRemoteSigns: -1 # Maximum number of remote signs that can be triggered at once.  Setting to -1 allows unlimited.
CraftsUseNetherPortals: false
RequireCreatePerm: false # require users to have the movecract.<CraftTypeName>.create permission in order to place command signs
RequireNamePerm: true # Require movecraft.name.place to place Name: signs and movecraft.name.use to use Name: signs
FadeWrecksAfter: 600 #T ime in seconds after which a craft wreck will start to fade after being sunk
FadeTickCooldown: 20 # Number of ticks between each fading cycle
FadePercentageOfWreckPerCycle: 10.0 # Percentage of wreck to be faded in each fading cycle
ExtraFadeTimePerBlock: # List of blocks that will take longer time to fade
  CHEST: 600
  TRAPPED_CHEST: 600
  DISPENSER: 600
  DROPPER: 600
  FURNACE: 600
CollisionPrimer: 1000
ForbiddenRemoteSigns: # These strings will be ignored when searching for signs to trigger from a remote sign
  - "Mounted"
  - "Denied"
  - "Remote Sign"
  - "[private]"
GeneratedDatapack: false # Set to false to re-generate datapack on startup

GearshiftsWithPilotToolEnabled: true #Allows Players to Change speeds via Sneak-Right Clicking with the Stick/Control-Item


# >>> EXPERIMENTAL ADDITION <<<
#The Following ONLY works if you are using the Paper Fork of:
#- https://github.com/SparklyPower/SparklyPaper
# Enables:
# Multiworld-Threading (TLDR; Large Crafts will move without extensively lagging the main thread of the server.)
IsMultithreaded: false
# >>> EXPERIMENTAL ADDITION <<<
